name: Publish Nugets

on:
  push:
    branches:
    - main    
    paths:
      - "Memoizer/**"
      - "Memoizer.sln"
    
jobs:
  pack_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*
    - name: Set PACKAGE_VERSION variable
      run: echo "PACKAGE_VERSION=$(date +'%Y.%-m.%-d').${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal      
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${PACKAGE_VERSION} --no-build --output .
    - name: PushNuget
      run: dotnet nuget push Memoizer.NETStandard.${PACKAGE_VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.PUBLISH_TO_NUGET_ORG}}   
    - name: PushGithub
      run: dotnet nuget push Memoizer.NETStandard.${PACKAGE_VERSION}.nupkg --source https://nuget.pkg.github.com/gaweph/index.json --api-key ${{secrets.GITHUB_TOKEN}}
