name: Push Github Nuget

on:
  push:
    branches:
    - main
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: "$(date +'%Y.%m.%-d').${GITHUB_RUN_NUMBER}"
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal      
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${PACKAGE_VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push Memoizer.NETStandard.${PACKAGE_VERSION}.nupkg --source https://nuget.pkg.github.com/gaweph/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
